### ISSUE TITLE
Add more resources under README.md

### ISSUE THREAD

**Issue by aakzsh** [GDSC-USICT/Git-Gud#10]
Add more resources related to open source and put them in a list with hyperlinks to their respective resource pages

**Comment by Ultimateutkarsh11** [comment]
Hey, please assign this issue to me, I am willing to work on it!

**Comment by aakzsh** [comment]
done, let me know if you have any doubts!

**Comment by Ultimateutkarsh11** [comment]
Sure, Thank you!

**Comment by aakzsh** [comment]
closing this issue as PR #12 fixes it
